# Turns the shader sources into a header of SPIR-V byte arrays.
#
# Three steps: run the probe to write the assembled sources, compile each one
# with glslangValidator, and emit the results as C arrays the Vulkan backend can
# hand straight to vkCreateShaderModule.
#
# Invoked by the build, not by hand. Expects PROBE, OUTDIR, VALIDATOR and HEADER.
#
# A failure here fails the build, which is the point: a shader that stops being
# valid Vulkan GLSL should not be discoverable only at runtime.

if(NOT VALIDATOR OR VALIDATOR MATCHES "NOTFOUND")
    message(FATAL_ERROR "glslangValidator not found. Install the Vulkan SDK, set VULKAN_SDK, or configure with -DCTR_NATIVE_VULKAN=OFF.")
endif()

file(REMOVE_RECURSE "${OUTDIR}")
file(MAKE_DIRECTORY "${OUTDIR}")

execute_process(
    COMMAND "${PROBE}" "${OUTDIR}"
    RESULT_VARIABLE probeResult
    OUTPUT_VARIABLE probeOutput
    ERROR_VARIABLE probeError
)

if(NOT probeResult EQUAL 0)
    message(FATAL_ERROR "shader source emitter failed (${probeResult}):\n${probeOutput}${probeError}")
endif()

file(GLOB shaders "${OUTDIR}/*.vert" "${OUTDIR}/*.frag")
list(SORT shaders)
list(LENGTH shaders total)

if(total EQUAL 0)
    message(FATAL_ERROR "shader source emitter wrote nothing to ${OUTDIR}")
endif()

set(arrays "")
set(index "")

foreach(shader IN LISTS shaders)
    get_filename_component(name "${shader}" NAME)

    execute_process(
        COMMAND "${VALIDATOR}" -V "${shader}" -o "${shader}.spv"
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error
    )

    if(NOT result EQUAL 0)
        message(FATAL_ERROR
            "${name} does not compile as Vulkan GLSL:\n${output}${error}\n"
            "The assembled source is at ${shader} - the line numbers above refer to it.\n"
            "A shader body used something the Vulkan preamble in tools/shader_spirv_probe.c "
            "does not accept, or that preamble has drifted from the one native_renderer.c builds "
            "at runtime. Those two are the same shader seen twice and must agree.")
    endif()

    # A file name is not an identifier. psx4_bilinear.frag -> psx4_bilinear_frag
    string(REPLACE "." "_" symbol "${name}")

    file(READ "${shader}.spv" hex HEX)
    string(REGEX MATCHALL ".." bytes "${hex}")
    list(LENGTH bytes byteCount)

    # SPIR-V is a stream of 32-bit words, not bytes. A module whose size is not
    # a whole number of words is truncated, and vkCreateShaderModule would
    # reject it later and less clearly.
    math(EXPR remainder "${byteCount} % 4")
    if(NOT remainder EQUAL 0)
        message(FATAL_ERROR "${name}.spv is ${byteCount} bytes, not a whole number of SPIR-V words")
    endif()

    # Emitted as words rather than bytes for two reasons. vkCreateShaderModule
    # takes a const uint32_t*, and casting a char array to that is only as
    # aligned as the compiler felt like being. It is also a quarter of the text.
    #
    # The four groups are reversed because the file is little-endian on disk and
    # these are integer literals, not a byte image.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])([0-9a-f][0-9a-f])" "0x\\4\\3\\2\\1u," joined "${hex}")

    math(EXPR wordCount "${byteCount} / 4")

    string(APPEND arrays "static const uint32_t g_spv_${symbol}[${wordCount}] = {${joined}};\n\n")
    string(APPEND index "    {\"${name}\", g_spv_${symbol}, ${byteCount}},\n")
endforeach()

set(contents
"// Generated by tools/build_shaders.cmake. Do not edit.
//
// SPIR-V for every shader stage, compiled from platform/native_shaders.inc.
// Look the module up by the name the emitter gave it - \"psx4.frag\",
// \"present_rt.vert\" and so on.

#ifndef CTR_NATIVE_SHADERS_SPV_H
#define CTR_NATIVE_SHADERS_SPV_H

#include <stdint.h>

${arrays}// size is in bytes, which is what VkShaderModuleCreateInfo::codeSize wants -
// the one place Vulkan measures SPIR-V in bytes rather than words.
typedef struct
{
	const char *name;
	const uint32_t *code;
	unsigned int size;
} NativeSpirvModule;

static const NativeSpirvModule g_spirvModules[] = {
${index}};

#define NATIVE_SPIRV_MODULE_COUNT ${total}

#endif
")

# Only rewrite when something changed, so a rebuild does not recompile the world
# for a header with identical contents.
set(previous "")
if(EXISTS "${HEADER}")
    file(READ "${HEADER}" previous)
endif()

if(NOT previous STREQUAL contents)
    file(WRITE "${HEADER}" "${contents}")
    message(STATUS "wrote ${HEADER} - ${total} SPIR-V modules")
else()
    message(STATUS "${HEADER} unchanged - ${total} SPIR-V modules")
endif()
