# Build ID at BUILD TIME (Beta 0, manual test 2026-09-29).
#
#   cmake -DOUT=<path/ctr_build_id.h> [-DSRC=<tree root>] [-DGIT=<git.exe>]
#         -P cmake/CtrBuildId.cmake
#
# Before, CTR_NATIVE_BUILD_ID was only created at configure time. A build after new
# commits kept carrying the old ID: the Alpha-Maker showed "Beta 0
# (<old id>)" although its code was newer - and the
# pairing check (Alpha-Maker <-> ctr_native.exe, paket-beta0.sh "pair ok")
# took two different states with the same old ID as a pair.
#
# Now this script runs on every build (target ctr_build_id in
# CMakeLists.txt) and writes the header only when its content changes.
# Same state = file untouched = nothing is recompiled.
#
# The ID:
#   <12 hex>                  clean tree, exactly as before (paket-beta0.sh)
#   <12 hex>-dirty-<6 hex>    tracked files differ from HEAD (staged
#                             changes too); the 6 hex are SHA-1 over
#                             "git diff HEAD --binary" - two different
#                             dirty states share no ID
#   <12 hex>-dirty            git diff itself failed
#   unknown                   no git, no repository
# Untracked files do not count, as with "git status --untracked-files=no".

if(NOT OUT)
    message(FATAL_ERROR "CtrBuildId.cmake: OUT (path of the header) is missing")
endif()
if(NOT SRC)
    get_filename_component(SRC "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT GIT)
    set(GIT git)
endif()

set(ctr_id "unknown")

# The header's folder must exist before the first write: the diff file
# below lies in it as well. In a fresh build folder (clone, CI) it does not
# exist yet otherwise, and file(SIZE) aborts the build.
get_filename_component(ctr_out_dir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${ctr_out_dir}")

execute_process(
    COMMAND "${GIT}" rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${SRC}"
    OUTPUT_VARIABLE ctr_hash
    RESULT_VARIABLE ctr_rc
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

if(ctr_rc EQUAL 0 AND ctr_hash)
    # The diff goes into a file, not into a variable: that way it stays
    # byte for byte what git writes, even with non-UTF-8 in text files.
    # Without colour, external diff tools and textconv - those would come from the
    # user configuration and do not depend on the state.
    set(ctr_diff "${OUT}.diff.tmp")
    execute_process(
        COMMAND "${GIT}" diff HEAD --binary --no-color --no-ext-diff --no-textconv
        WORKING_DIRECTORY "${SRC}"
        OUTPUT_FILE "${ctr_diff}"
        RESULT_VARIABLE ctr_diff_rc
        ERROR_QUIET
    )
    if(NOT ctr_diff_rc EQUAL 0)
        set(ctr_id "${ctr_hash}-dirty")
    else()
        file(SIZE "${ctr_diff}" ctr_diff_size)
        if(ctr_diff_size EQUAL 0)
            set(ctr_id "${ctr_hash}")
        else()
            file(SHA1 "${ctr_diff}" ctr_diff_sha)
            string(SUBSTRING "${ctr_diff_sha}" 0 6 ctr_diff_short)
            set(ctr_id "${ctr_hash}-dirty-${ctr_diff_short}")
        endif()
    endif()
    file(REMOVE "${ctr_diff}")
endif()

set(ctr_text "// Generated by cmake/CtrBuildId.cmake on every build - do not edit by hand.
#ifndef CTR_BUILD_ID_H
#define CTR_BUILD_ID_H
#define CTR_NATIVE_BUILD_ID \"${ctr_id}\"
#endif
")

# Write only when the content is new: it is the timestamp that makes the consumers
# recompile.
set(ctr_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" ctr_old)
endif()
if(NOT ctr_old STREQUAL ctr_text)
    get_filename_component(ctr_dir "${OUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${ctr_dir}")
    file(WRITE "${OUT}" "${ctr_text}")
    message(STATUS "Build ID: ${ctr_id}")
endif()
